version: '2'

services:
  spark:
    build: ./spark
    hostname: spark
    container_name: spark
    ports: 
      - 9102:9100

  namenode:
    build: ./namenode
    hostname: namenode
    container_name: namenode

  datanode1:
    build: ./datanode
    hostname: datanode1
    container_name: datanode1
    depends_on:
      - "namenode"
    links:
      - "namenode"

  resourcemanager:
    build: ./resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    ports:
      - 8088:8088
    depends_on:
      - "namenode"
    links:
      - "namenode"

  nodemanager1:
    build: ./nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    ports: 
      - 9101:9100
    depends_on:
      - "namenode"
      - "resourcemanager"
    links:
      - "namenode"
      - "resourcemanager"