version: '2'

services:
  spark:
    build: ./spark
    hostname: spark
    container_name: spark

  namenode:
    build: ./namenode
    hostname: namenode
    container_name: namenode

  datanode1:
    build: ./datanode
    hostname: datanode1
    container_name: datanode1
    depends_on:
      - "namenode"
    links:
      - "namenode"

  datanode2:
    build: ./datanode
    hostname: datanode2
    container_name: datanode2
    depends_on:
      - "namenode"
    links:
      - "namenode"


  resourcemanager:
    build: ./resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    ports:
      - 8088:8088
    depends_on:
      - "namenode"
    links:
      - "namenode"

  nodemanager1:
    build: ./nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    depends_on:
      - "namenode"
      - "resourcemanager"
    links:
      - "namenode"
      - "resourcemanager"

  nodemanager2:
    build: ./nodemanager
    hostname: nodemanager2
    container_name: nodemanager2
    depends_on:
      - "namenode"
      - "resourcemanager"
    links:
      - "namenode"
      - "resourcemanager"